#!/usr/bin/env bash

if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  SCRIPT_PATH="${BASH_SOURCE[0]}"
elif [[ -n "${ZSH_VERSION:-}" ]]; then
  SCRIPT_PATH="${(%):-%x}"
else
  SCRIPT_PATH="$0"
fi

SCRIPT_DIR="$(cd "$(dirname "${SCRIPT_PATH}")" && pwd)"
LOCAL_DIR="${SCRIPT_DIR}"
REPO_ROOT="$(cd "${LOCAL_DIR}/.." && pwd)"
COMPOSE_FILE="${LOCAL_DIR}/docker-compose.yaml"

COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-lightspeed-dev}"

POSTGRES_USER="${POSTGRES_USER:-lightspeed}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-lightspeed}"
POSTGRES_DB="${POSTGRES_DB:-lightspeed}"
POSTGRES_PORT="${POSTGRES_PORT:-15432}"

PGADMIN_PORT="${PGADMIN_PORT:-15080}"
PGADMIN_DEFAULT_EMAIL="${PGADMIN_DEFAULT_EMAIL:-admin@lightspeed.dev}"
PGADMIN_DEFAULT_PASSWORD="${PGADMIN_DEFAULT_PASSWORD:-lightspeed}"

MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-minioadmin}"
MINIO_API_PORT="${MINIO_API_PORT:-29000}"
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-29001}"

TEMPORAL_PORT="${TEMPORAL_PORT:-7233}"
TEMPORAL_UI_PORT="${TEMPORAL_UI_PORT:-8233}"

LIGHTSPEED_TEST_POSTGRES_URL="${LIGHTSPEED_TEST_POSTGRES_URL:-postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}}"
LIGHTSPEED_PG_UNIVERSE_ID="${LIGHTSPEED_PG_UNIVERSE_ID:-00000000-0000-0000-0000-000000000001}"
LIGHTSPEED_POSTGRES_URL="${LIGHTSPEED_POSTGRES_URL:-${LIGHTSPEED_TEST_POSTGRES_URL}}"
LIGHTSPEED_TASK_QUEUE="${LIGHTSPEED_TASK_QUEUE:-lightspeed-agent}"
LIGHTSPEED_API_URL="${LIGHTSPEED_API_URL:-http://127.0.0.1:18080/rpc}"

LIGHTSPEED_OBJECT_STORE_BUCKET="${LIGHTSPEED_OBJECT_STORE_BUCKET:-lightspeed-dev}"
LIGHTSPEED_OBJECT_STORE_ENDPOINT="${LIGHTSPEED_OBJECT_STORE_ENDPOINT:-http://localhost:${MINIO_API_PORT}}"
LIGHTSPEED_OBJECT_STORE_REGION="${LIGHTSPEED_OBJECT_STORE_REGION:-us-east-1}"
LIGHTSPEED_OBJECT_STORE_PREFIX="${LIGHTSPEED_OBJECT_STORE_PREFIX:-lightspeed}"
LIGHTSPEED_OBJECT_STORE_FORCE_PATH_STYLE="${LIGHTSPEED_OBJECT_STORE_FORCE_PATH_STYLE:-true}"

# AES-256-GCM master key for the store-pg secret store (base64, 32 bytes).
# This is a well-known LOCAL DEVELOPMENT key ("lightspeed-local-dev-master-key-0001!")
# so secrets survive shell restarts; never use it outside local dev. The key is
# fixed rather than random because changing it makes previously stored secrets
# undecryptable.
LIGHTSPEED_DEV_SECRETS_MASTER_KEY_DEFAULT="Zm9yZ2UtbG9jYWwtZGV2LW1hc3Rlci1rZXktMDAwMSE="
LIGHTSPEED_SECRETS_MASTER_KEY="${LIGHTSPEED_SECRETS_MASTER_KEY:-${LIGHTSPEED_DEV_SECRETS_MASTER_KEY_DEFAULT}}"

export COMPOSE_PROJECT_NAME
export POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_PORT
export PGADMIN_PORT PGADMIN_DEFAULT_EMAIL PGADMIN_DEFAULT_PASSWORD
export MINIO_ROOT_USER MINIO_ROOT_PASSWORD MINIO_API_PORT MINIO_CONSOLE_PORT
export TEMPORAL_PORT TEMPORAL_UI_PORT

compose() {
  docker compose -f "${COMPOSE_FILE}" "$@"
}
