#!/usr/bin/env bash

if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  SCRIPT_PATH="${BASH_SOURCE[0]}"
elif [[ -n "${ZSH_VERSION:-}" ]]; then
  SCRIPT_PATH="${(%):-%x}"
else
  SCRIPT_PATH="$0"
fi

SCRIPT_DIR="$(cd "$(dirname "${SCRIPT_PATH}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

export LIGHTSPEED_TEST_POSTGRES_URL
export LIGHTSPEED_PG_UNIVERSE_ID
export LIGHTSPEED_POSTGRES_URL
export LIGHTSPEED_TASK_QUEUE
export LIGHTSPEED_API_URL
export LIGHTSPEED_OBJECT_STORE_BUCKET
export LIGHTSPEED_OBJECT_STORE_ENDPOINT
export LIGHTSPEED_OBJECT_STORE_REGION
export LIGHTSPEED_OBJECT_STORE_PREFIX
export LIGHTSPEED_OBJECT_STORE_FORCE_PATH_STYLE
export LIGHTSPEED_SECRETS_MASTER_KEY
export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-${MINIO_ROOT_USER}}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-${MINIO_ROOT_PASSWORD}}"

echo "Lightspeed local env exported:"
echo "  LIGHTSPEED_TEST_POSTGRES_URL=${LIGHTSPEED_TEST_POSTGRES_URL}"
echo "  LIGHTSPEED_PG_UNIVERSE_ID=${LIGHTSPEED_PG_UNIVERSE_ID}"
echo "  LIGHTSPEED_POSTGRES_URL=${LIGHTSPEED_POSTGRES_URL}"
echo "  LIGHTSPEED_TASK_QUEUE=${LIGHTSPEED_TASK_QUEUE}"
echo "  LIGHTSPEED_API_URL=${LIGHTSPEED_API_URL}"
echo "  LIGHTSPEED_OBJECT_STORE_BUCKET=${LIGHTSPEED_OBJECT_STORE_BUCKET}"
echo "  LIGHTSPEED_OBJECT_STORE_ENDPOINT=${LIGHTSPEED_OBJECT_STORE_ENDPOINT}"
echo "  LIGHTSPEED_OBJECT_STORE_PREFIX=${LIGHTSPEED_OBJECT_STORE_PREFIX}"
if [[ "${LIGHTSPEED_SECRETS_MASTER_KEY}" == "${LIGHTSPEED_DEV_SECRETS_MASTER_KEY_DEFAULT}" ]]; then
  echo "  LIGHTSPEED_SECRETS_MASTER_KEY=(local dev default)"
else
  echo "  LIGHTSPEED_SECRETS_MASTER_KEY=(custom, redacted)"
fi
