#!/usr/bin/env bash

if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  SCRIPT_PATH="${BASH_SOURCE[0]}"
elif [[ -n "${ZSH_VERSION:-}" ]]; then
  SCRIPT_PATH="${(%):-%x}"
else
  SCRIPT_PATH="$0"
fi

SCRIPT_DIR="$(cd "$(dirname "${SCRIPT_PATH}")" && pwd)"
DEV_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${DEV_DIR}/.." && pwd)"
COMPOSE_FILE="${DEV_DIR}/docker-compose.yaml"

COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-forge-dev}"

POSTGRES_USER="${POSTGRES_USER:-forge}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-forge}"
POSTGRES_DB="${POSTGRES_DB:-forge}"
POSTGRES_PORT="${POSTGRES_PORT:-15432}"

PGADMIN_PORT="${PGADMIN_PORT:-15080}"

MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-minioadmin}"
MINIO_API_PORT="${MINIO_API_PORT:-29000}"
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-29001}"

TEMPORAL_PORT="${TEMPORAL_PORT:-7233}"
TEMPORAL_UI_PORT="${TEMPORAL_UI_PORT:-8233}"

FORGE_TEST_POSTGRES_URL="${FORGE_TEST_POSTGRES_URL:-postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}}"
FORGE_PG_UNIVERSE_ID="${FORGE_PG_UNIVERSE_ID:-00000000-0000-0000-0000-000000000001}"
FORGE_POSTGRES_URL="${FORGE_POSTGRES_URL:-${FORGE_TEST_POSTGRES_URL}}"
FORGE_TASK_QUEUE="${FORGE_TASK_QUEUE:-forge-agent}"
FORGE_LLM="${FORGE_LLM:-fake}"
FORGE_API_URL="${FORGE_API_URL:-http://127.0.0.1:18080/rpc}"

FORGE_OBJECT_STORE_BUCKET="${FORGE_OBJECT_STORE_BUCKET:-forge-dev}"
FORGE_OBJECT_STORE_ENDPOINT="${FORGE_OBJECT_STORE_ENDPOINT:-http://localhost:${MINIO_API_PORT}}"
FORGE_OBJECT_STORE_REGION="${FORGE_OBJECT_STORE_REGION:-us-east-1}"
FORGE_OBJECT_STORE_PREFIX="${FORGE_OBJECT_STORE_PREFIX:-forge}"
FORGE_OBJECT_STORE_FORCE_PATH_STYLE="${FORGE_OBJECT_STORE_FORCE_PATH_STYLE:-true}"

export COMPOSE_PROJECT_NAME
export POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_PORT
export PGADMIN_PORT
export MINIO_ROOT_USER MINIO_ROOT_PASSWORD MINIO_API_PORT MINIO_CONSOLE_PORT
export TEMPORAL_PORT TEMPORAL_UI_PORT

compose() {
  docker compose -f "${COMPOSE_FILE}" "$@"
}
