#!/usr/bin/env bash

if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  SCRIPT_PATH="${BASH_SOURCE[0]}"
elif [[ -n "${ZSH_VERSION:-}" ]]; then
  SCRIPT_PATH="${(%):-%x}"
else
  SCRIPT_PATH="$0"
fi

SCRIPT_DIR="$(cd "$(dirname "${SCRIPT_PATH}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

export FORGE_TEST_POSTGRES_URL
export FORGE_PG_UNIVERSE_ID
export FORGE_POSTGRES_URL
export FORGE_TASK_QUEUE
export FORGE_LLM
export FORGE_API_URL
export FORGE_OBJECT_STORE_BUCKET
export FORGE_OBJECT_STORE_ENDPOINT
export FORGE_OBJECT_STORE_REGION
export FORGE_OBJECT_STORE_PREFIX
export FORGE_OBJECT_STORE_FORCE_PATH_STYLE
export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-${MINIO_ROOT_USER}}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-${MINIO_ROOT_PASSWORD}}"

echo "Forge local env exported:"
echo "  FORGE_TEST_POSTGRES_URL=${FORGE_TEST_POSTGRES_URL}"
echo "  FORGE_PG_UNIVERSE_ID=${FORGE_PG_UNIVERSE_ID}"
echo "  FORGE_POSTGRES_URL=${FORGE_POSTGRES_URL}"
echo "  FORGE_TASK_QUEUE=${FORGE_TASK_QUEUE}"
echo "  FORGE_LLM=${FORGE_LLM}"
echo "  FORGE_API_URL=${FORGE_API_URL}"
echo "  FORGE_OBJECT_STORE_BUCKET=${FORGE_OBJECT_STORE_BUCKET}"
echo "  FORGE_OBJECT_STORE_ENDPOINT=${FORGE_OBJECT_STORE_ENDPOINT}"
echo "  FORGE_OBJECT_STORE_PREFIX=${FORGE_OBJECT_STORE_PREFIX}"
