import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const interopDir = path.resolve(packageDir, "..");
const manifestPath = path.join(interopDir, "contract", "methods.json");
const schemaPath = path.join(interopDir, "contract", "api.schema.json");
const filterPath = path.join(packageDir, "tool-filter.json");
const outputPath = path.join(packageDir, "src", "generated", "tools.ts");

const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
const bundle = JSON.parse(await readFile(schemaPath, "utf8"));
const filter = JSON.parse(await readFile(filterPath, "utf8"));
const definitions = bundle.definitions ?? {};
const universeMethods = (manifest.methods ?? []).filter((entry) => entry.scope === "universe");
const excludeMethods = validateFilter(filter, universeMethods);
const methods = universeMethods.filter((entry) => !excludeMethods.has(entry.method));

const seenNames = new Map();
const tools = methods.map((entry) => {
  const name = toolName(entry.method);
  const prior = seenNames.get(name);
  if (prior) {
    throw new Error(`MCP tool name collision: ${name} for ${prior} and ${entry.method}`);
  }
  seenNames.set(name, entry.method);
  return {
    name,
    method: entry.method,
    paramsType: entry.params.type,
    resultType: entry.result.type,
    inputSchema: standaloneSchema(entry.params.schema, entry.method, "params"),
  };
});

for (const entry of manifest.methods ?? []) {
  if (entry.scope === "operator" && tools.some((tool) => tool.method === entry.method)) {
    throw new Error(`operator method leaked into MCP tools: ${entry.method}`);
  }
}

const banner = [
  "/*",
  " * Generated by interop/configurator-mcp/scripts/generate-tools.mjs.",
  " * Do not edit by hand.",
  " */",
  'import type { GeneratedToolDescriptor } from "../tool-descriptor.js";',
  "",
  `export const GENERATED_TOOLS: readonly GeneratedToolDescriptor[] = ${JSON.stringify(tools, null, 2)};`,
  "",
].join("\n");

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, banner);

function validateFilter(value, universeEntries) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("tool-filter.json must contain one JSON object");
  }
  const keys = Object.keys(value);
  if (keys.some((key) => key !== "excludeMethods")) {
    const unknownKeys = keys.filter((key) => key !== "excludeMethods");
    throw new Error(`tool-filter.json has unknown keys: ${unknownKeys.join(", ")}`);
  }
  if (!Array.isArray(value.excludeMethods)) {
    throw new Error("tool-filter.json excludeMethods must be an array");
  }
  const excluded = new Set();
  for (const method of value.excludeMethods) {
    if (typeof method !== "string" || method.length === 0) {
      throw new Error("tool-filter.json excludeMethods entries must be non-empty strings");
    }
    if (excluded.has(method)) {
      throw new Error(`tool-filter.json contains duplicate method: ${method}`);
    }
    excluded.add(method);
  }
  const universeNames = new Set(universeEntries.map((entry) => entry.method));
  const unknown = [...excluded].filter((method) => !universeNames.has(method));
  if (unknown.length > 0) {
    throw new Error(
      `tool-filter.json excludes unknown or non-universe methods: ${unknown.join(", ")}`,
    );
  }
  return excluded;
}

function toolName(method) {
  return `lightspeed_${method.replaceAll(/[^A-Za-z0-9_-]/g, "_")}`;
}

function standaloneSchema(schema, method, side) {
  const root = dereferenceRoot(schema, method, side);
  const reachable = new Set();
  collectDefinitionRefs(root, reachable);
  const pending = [...reachable];
  for (let index = 0; index < pending.length; index += 1) {
    const name = pending[index];
    const definition = definitions[name];
    if (!definition) {
      throw new Error(`${method} ${side} references missing definition ${name}`);
    }
    const nested = new Set();
    collectDefinitionRefs(definition, nested);
    for (const child of nested) {
      if (!reachable.has(child)) {
        reachable.add(child);
        pending.push(child);
      }
    }
  }

  const selected = {};
  for (const name of [...reachable].sort()) {
    selected[name] = definitions[name];
  }

  return normalizeBooleanSchemas({
    $schema: "http://json-schema.org/draft-07/schema#",
    ...root,
    ...(Object.keys(selected).length > 0 ? { definitions: selected } : {}),
  });
}

function dereferenceRoot(schema, method, side) {
  const reference = schema?.$ref;
  const prefix = "#/definitions/";
  if (typeof reference !== "string" || !reference.startsWith(prefix)) {
    throw new Error(`${method} ${side} schema is not a definitions ref`);
  }
  const name = reference.slice(prefix.length);
  const definition = definitions[name];
  if (!definition) {
    throw new Error(`${method} ${side} references missing root definition ${name}`);
  }
  return structuredClone(definition);
}

function collectDefinitionRefs(value, output) {
  if (Array.isArray(value)) {
    for (const entry of value) {
      collectDefinitionRefs(entry, output);
    }
    return;
  }
  if (!value || typeof value !== "object") {
    return;
  }
  for (const [key, entry] of Object.entries(value)) {
    if (key === "$ref" && typeof entry === "string") {
      const prefix = "#/definitions/";
      if (entry.startsWith(prefix)) {
        output.add(entry.slice(prefix.length));
      }
    } else {
      collectDefinitionRefs(entry, output);
    }
  }
}

// MCP's Tool schema shape accepts JSON Schema objects in `properties`, while
// draft-07 also permits boolean schemas. Preserve their semantics in object
// form so the SDK and clients accept the advertised tool descriptor.
function normalizeBooleanSchemas(value) {
  if (value === true) {
    return {};
  }
  if (value === false) {
    return { not: {} };
  }
  if (Array.isArray(value)) {
    return value.map(normalizeBooleanSchemas);
  }
  if (!value || typeof value !== "object") {
    return value;
  }
  return Object.fromEntries(
    Object.entries(value).map(([key, entry]) => [key, normalizeBooleanSchemas(entry)]),
  );
}
