use std::path::PathBuf;

use anyhow::Result;
use clap::{Args, Subcommand, ValueEnum};

use crate::api_client::HttpAgentApi;
use crate::vfs_transfer::{
    DEFAULT_HAS_MANY_MAX_REFS, DEFAULT_MAX_DEPTH, DEFAULT_MAX_FILES, DEFAULT_MAX_SINGLE_FILE_BYTES,
    DEFAULT_MAX_TOTAL_BYTES, DEFAULT_PUT_MANY_MAX_BATCH_BYTES, DEFAULT_PUT_MANY_MAX_BATCH_FILES,
    SnapshotUploadOptions, materialize_snapshot, upload_snapshot_directory,
};

#[derive(Args, Debug, Clone)]
pub(crate) struct VfsArgs {
    #[command(subcommand)]
    command: VfsCommand,
}

#[derive(Subcommand, Debug, Clone)]
enum VfsCommand {
    /// Upload a local directory as a CAS-backed VFS snapshot.
    Snapshot(SnapshotArgs),
    /// Materialize a CAS-backed VFS snapshot into a local directory.
    Materialize(MaterializeArgs),
    /// Manage VFS workspaces.
    Workspace(WorkspaceArgs),
    /// Manage session VFS mounts.
    Mount(MountArgs),
}

#[derive(Args, Debug, Clone)]
struct SnapshotArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit the snapshot summary as JSON.
    #[arg(long)]
    json: bool,
    /// Max raw bytes per blobs/put request.
    #[arg(long = "put-batch-bytes", default_value_t = DEFAULT_PUT_MANY_MAX_BATCH_BYTES)]
    put_batch_bytes: u64,
    /// Max blobs per blobs/put request.
    #[arg(long = "put-batch-files", default_value_t = DEFAULT_PUT_MANY_MAX_BATCH_FILES)]
    put_batch_files: usize,
    /// Max refs per blobs/has request.
    #[arg(long = "has-batch-refs", default_value_t = DEFAULT_HAS_MANY_MAX_REFS)]
    has_batch_refs: usize,
    /// Max file count in the snapshot.
    #[arg(long = "max-files", default_value_t = DEFAULT_MAX_FILES)]
    max_files: u64,
    /// Max total file bytes in the snapshot.
    #[arg(long = "max-total-bytes", default_value_t = DEFAULT_MAX_TOTAL_BYTES)]
    max_total_bytes: u64,
    /// Max single file bytes in the snapshot.
    #[arg(long = "max-file-bytes", default_value_t = DEFAULT_MAX_SINGLE_FILE_BYTES)]
    max_file_bytes: u64,
    /// Max VFS path depth in the snapshot.
    #[arg(long = "max-depth", default_value_t = DEFAULT_MAX_DEPTH)]
    max_depth: usize,
    /// Local directory to snapshot.
    directory: PathBuf,
}

#[derive(Args, Debug, Clone)]
struct MaterializeArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit the materialization summary as JSON.
    #[arg(long)]
    json: bool,
    /// Read the snapshot through this workspace, whose current head or base
    /// it must be; its files come from the workspace head. Needed for a
    /// snapshot someone else uploaded.
    #[arg(long)]
    workspace: Option<String>,
    /// Snapshot ref to materialize.
    snapshot_ref: String,
    /// Local destination directory.
    destination: PathBuf,
}

#[derive(Args, Debug, Clone)]
struct WorkspaceArgs {
    #[command(subcommand)]
    command: WorkspaceCommand,
}

#[derive(Subcommand, Debug, Clone)]
enum WorkspaceCommand {
    /// Create a VFS workspace from a snapshot ref.
    Create(WorkspaceCreateArgs),
    /// Read the current head of a VFS workspace.
    Read(WorkspaceReadArgs),
    /// List all VFS workspaces in the universe.
    List(WorkspaceListArgs),
    /// Advance a VFS workspace head to a new snapshot ref.
    Update(WorkspaceUpdateArgs),
    /// Delete a VFS workspace.
    Delete(WorkspaceDeleteArgs),
}

#[derive(Args, Debug, Clone)]
struct WorkspaceCreateArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit the workspace summary as JSON.
    #[arg(long)]
    json: bool,
    /// Optional workspace id. Generated by the gateway when omitted.
    #[arg(long = "workspace-id")]
    workspace_id: Option<String>,
    /// Optional display name for snapshot catalog metadata.
    #[arg(long = "display-name")]
    display_name: Option<String>,
    /// Snapshot ref for the workspace base/head. Omitted starts the
    /// workspace from the empty snapshot.
    snapshot_ref: Option<String>,
}

#[derive(Args, Debug, Clone)]
struct WorkspaceListArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit the workspace list as JSON.
    #[arg(long)]
    json: bool,
}

#[derive(Args, Debug, Clone)]
struct WorkspaceReadArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit the workspace summary as JSON.
    #[arg(long)]
    json: bool,
    /// Workspace id to read.
    workspace_id: String,
}

#[derive(Args, Debug, Clone)]
struct WorkspaceUpdateArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit the workspace summary as JSON.
    #[arg(long)]
    json: bool,
    /// Expected current workspace revision. Omit for last-writer-wins.
    #[arg(long = "expected-revision")]
    expected_revision: Option<u64>,
    /// Optional display name for snapshot catalog metadata.
    #[arg(long = "display-name")]
    display_name: Option<String>,
    /// Workspace id to update.
    workspace_id: String,
    /// New snapshot ref for the workspace head.
    snapshot_ref: String,
}

#[derive(Args, Debug, Clone)]
struct WorkspaceDeleteArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit the deleted workspace summary as JSON.
    #[arg(long)]
    json: bool,
    /// Workspace id to delete.
    workspace_id: String,
}

#[derive(Args, Debug, Clone)]
struct MountArgs {
    #[command(subcommand)]
    command: MountCommand,
}

#[derive(Subcommand, Debug, Clone)]
enum MountCommand {
    /// Attach a snapshot or workspace to a session VFS path.
    Put(MountPutArgs),
    /// Remove a VFS mount from a session path.
    Delete(MountDeleteArgs),
    /// List VFS mounts for a session.
    List(MountListArgs),
}

#[derive(Args, Debug, Clone)]
struct MountPutArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit the mount summary as JSON.
    #[arg(long)]
    json: bool,
    /// Session id to mount into.
    #[arg(long)]
    session: String,
    /// VFS mount path.
    #[arg(long = "path")]
    mount_path: String,
    /// Workspace id to mount.
    #[arg(long, conflicts_with = "snapshot")]
    workspace: Option<String>,
    /// Snapshot ref to mount; snapshots are immutable and always `read`.
    #[arg(long, conflicts_with = "workspace")]
    snapshot: Option<String>,
    /// Access granted on the attachment. Defaults to `edit` for workspaces
    /// and `read` for snapshots; `edit` is invalid for snapshots.
    #[arg(long, value_enum)]
    access: Option<MountAccess>,
}

#[derive(ValueEnum, Debug, Clone, Copy, PartialEq, Eq)]
enum MountAccess {
    Read,
    Edit,
}

impl From<MountAccess> for api::WorkspaceAccess {
    fn from(access: MountAccess) -> Self {
        match access {
            MountAccess::Read => api::WorkspaceAccess::Read,
            MountAccess::Edit => api::WorkspaceAccess::Edit,
        }
    }
}

#[derive(Args, Debug, Clone)]
struct MountDeleteArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit the deleted mount summary as JSON.
    #[arg(long)]
    json: bool,
    /// Session id to remove the mount from.
    #[arg(long)]
    session: String,
    /// VFS mount path to remove.
    #[arg(long = "path")]
    mount_path: String,
}

#[derive(Args, Debug, Clone)]
struct MountListArgs {
    /// JSON-RPC agent API URL.
    #[arg(long = "api-url", env = "LIGHTSPEED_API_URL")]
    api_url: String,
    /// Emit mounts as JSON.
    #[arg(long)]
    json: bool,
    /// Session id to inspect.
    #[arg(long)]
    session: String,
}

pub(crate) async fn handle(args: VfsArgs) -> Result<()> {
    match args.command {
        VfsCommand::Snapshot(args) => snapshot(args).await,
        VfsCommand::Materialize(args) => materialize(args).await,
        VfsCommand::Workspace(args) => workspace(args).await,
        VfsCommand::Mount(args) => mount(args).await,
    }
}

async fn snapshot(args: SnapshotArgs) -> Result<()> {
    let options = snapshot_options(&args);
    let api = HttpAgentApi::new(args.api_url);
    let summary = upload_snapshot_directory(&api, args.directory, options).await?;
    if args.json {
        println!("{}", serde_json::to_string_pretty(&summary)?);
        return Ok(());
    }

    println!("snapshotRef {}", summary.snapshot_ref);
    println!("files {}", summary.files);
    println!("bytes {}", summary.bytes);
    println!("uploadedBlobs {}", summary.uploaded_blobs);
    println!("uploadedBytes {}", summary.uploaded_bytes);
    println!("reusedBlobs {}", summary.reused_blobs);
    println!("reusedBytes {}", summary.reused_bytes);
    if summary.skipped_paths > 0 {
        println!("skippedPaths {}", summary.skipped_paths);
        for warning in summary.warnings {
            println!("warning {}: {}", warning.path, warning.message);
        }
    }
    Ok(())
}

async fn workspace(args: WorkspaceArgs) -> Result<()> {
    match args.command {
        WorkspaceCommand::Create(args) => workspace_create(args).await,
        WorkspaceCommand::Read(args) => workspace_read(args).await,
        WorkspaceCommand::List(args) => workspace_list(args).await,
        WorkspaceCommand::Update(args) => workspace_update(args).await,
        WorkspaceCommand::Delete(args) => workspace_delete(args).await,
    }
}

async fn workspace_create(args: WorkspaceCreateArgs) -> Result<()> {
    let api = HttpAgentApi::new(args.api_url);
    let response = api
        .create_vfs_workspace(api::VfsWorkspaceCreateParams {
            access: None,
            workspace_id: args.workspace_id,
            snapshot_ref: args.snapshot_ref,
            display_name: args.display_name,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result;
    print_workspace(response.workspace, args.json)
}

async fn workspace_list(args: WorkspaceListArgs) -> Result<()> {
    let api = HttpAgentApi::new(args.api_url);
    let response = api
        .list_vfs_workspaces(api::VfsWorkspaceListParams {})
        .await
        .map_err(crate::api_client::api_error)?
        .result;
    if args.json {
        println!("{}", serde_json::to_string_pretty(&response.workspaces)?);
        return Ok(());
    }
    for workspace in response.workspaces {
        let display_name = workspace.display_name.as_deref().unwrap_or("-");
        println!(
            "{} {} files {} bytes {} revision {}",
            workspace.workspace_id,
            display_name,
            workspace.files,
            workspace.bytes,
            workspace.revision
        );
    }
    Ok(())
}

async fn workspace_read(args: WorkspaceReadArgs) -> Result<()> {
    let api = HttpAgentApi::new(args.api_url);
    let workspace = api
        .read_vfs_workspace(api::VfsWorkspaceReadParams {
            workspace_id: args.workspace_id,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result
        .workspace;
    print_workspace(workspace, args.json)
}

async fn workspace_update(args: WorkspaceUpdateArgs) -> Result<()> {
    let api = HttpAgentApi::new(args.api_url);
    let workspace = api
        .update_vfs_workspace(api::VfsWorkspaceUpdateParams {
            workspace_id: args.workspace_id,
            expected_revision: args.expected_revision,
            snapshot_ref: args.snapshot_ref,
            display_name: args.display_name,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result
        .workspace;
    print_workspace(workspace, args.json)
}

async fn workspace_delete(args: WorkspaceDeleteArgs) -> Result<()> {
    let api = HttpAgentApi::new(args.api_url);
    let workspace = api
        .delete_vfs_workspace(api::VfsWorkspaceDeleteParams {
            workspace_id: args.workspace_id,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result
        .workspace;
    print_workspace(workspace, args.json)
}

fn print_workspace(workspace: api::VfsWorkspaceView, json: bool) -> Result<()> {
    if json {
        println!("{}", serde_json::to_string_pretty(&workspace)?);
        return Ok(());
    }

    println!("workspaceId {}", workspace.workspace_id);
    if let Some(display_name) = workspace.display_name {
        println!("displayName {display_name}");
    }
    println!("headSnapshotRef {}", workspace.head_snapshot_ref);
    if let Some(base) = workspace.base_snapshot_ref {
        println!("baseSnapshotRef {base}");
    }
    println!("files {}", workspace.files);
    println!("bytes {}", workspace.bytes);
    println!("revision {}", workspace.revision);
    Ok(())
}

async fn mount(args: MountArgs) -> Result<()> {
    match args.command {
        MountCommand::Put(args) => mount_put(args).await,
        MountCommand::Delete(args) => mount_delete(args).await,
        MountCommand::List(args) => mount_list(args).await,
    }
}

async fn mount_put(args: MountPutArgs) -> Result<()> {
    let (workspace_id, snapshot_ref) = match (args.workspace, args.snapshot) {
        (Some(workspace_id), None) => (Some(workspace_id), None),
        (None, Some(snapshot_ref)) => (None, Some(snapshot_ref)),
        _ => anyhow::bail!("exactly one of --workspace or --snapshot is required"),
    };
    let access = match (
        snapshot_ref.is_some(),
        args.access.map(api::WorkspaceAccess::from),
    ) {
        (true, Some(api::WorkspaceAccess::Edit)) => {
            anyhow::bail!("snapshot attachments cannot be edit; they are always read")
        }
        (true, _) => api::WorkspaceAccess::Read,
        (false, access) => access.unwrap_or(api::WorkspaceAccess::Edit),
    };
    let api = HttpAgentApi::new(args.api_url);
    let attachment = api::WorkspaceAttachment {
        path: args.mount_path,
        workspace_id,
        snapshot_ref,
        access,
    };
    let response = put_workspace_attachment(&api, args.session, attachment.clone()).await?;
    if args.json {
        println!("{}", serde_json::to_string_pretty(&response)?);
        return Ok(());
    }

    print_workspace_attachment(&attachment);
    println!("session {}", response.session.id);
    Ok(())
}

async fn mount_delete(args: MountDeleteArgs) -> Result<()> {
    let api = HttpAgentApi::new(args.api_url);
    let session = api
        .read_session(api::SessionReadParams {
            session_id: args.session.clone(),
            run_limit: None,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result
        .session;
    let mut config = session
        .config
        .ok_or_else(|| anyhow::anyhow!("session is missing config"))?;
    let vfs = config
        .features
        .as_mut()
        .and_then(|features| features.vfs.as_mut())
        .ok_or_else(|| anyhow::anyhow!("session does not grant VFS"))?;
    let before = vfs.workspaces.len();
    vfs.workspaces
        .retain(|attachment| attachment.path != args.mount_path);
    if vfs.workspaces.len() == before {
        anyhow::bail!("workspace attachment not found at {}", args.mount_path);
    }
    let response = api
        .put_session_config(api::SessionConfigPutParams {
            session_id: args.session,
            expected_config_revision: Some(session.config_revision),
            config,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result;
    if args.json {
        println!("{}", serde_json::to_string_pretty(&response)?);
        return Ok(());
    }

    println!("deleted {}", args.mount_path);
    println!("session {}", response.session.id);
    Ok(())
}

async fn mount_list(args: MountListArgs) -> Result<()> {
    let api = HttpAgentApi::new(args.api_url);
    let session = api
        .read_session(api::SessionReadParams {
            session_id: args.session,
            run_limit: None,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result
        .session;
    let attachments = session
        .config
        .and_then(|config| config.features)
        .and_then(|features| features.vfs)
        .map(|vfs| vfs.workspaces)
        .unwrap_or_default();
    if args.json {
        println!("{}", serde_json::to_string_pretty(&attachments)?);
        return Ok(());
    }

    for attachment in &attachments {
        print_workspace_attachment(attachment);
    }
    Ok(())
}

pub(crate) async fn create_workspace_from_snapshot(
    api: &HttpAgentApi,
    snapshot_ref: String,
) -> Result<api::VfsWorkspaceView> {
    Ok(api
        .create_vfs_workspace(api::VfsWorkspaceCreateParams {
            access: None,
            workspace_id: None,
            snapshot_ref: Some(snapshot_ref),
            display_name: None,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result
        .workspace)
}

pub(crate) async fn mount_workspace(
    api: &HttpAgentApi,
    session_id: String,
    mount_path: String,
    workspace_id: String,
    access: api::WorkspaceAccess,
) -> Result<api::SessionConfigPutResponse> {
    put_workspace_attachment(
        api,
        session_id,
        api::WorkspaceAttachment {
            path: mount_path,
            workspace_id: Some(workspace_id),
            snapshot_ref: None,
            access,
        },
    )
    .await
}

/// Workspace attachments are declarative session config: mount put/delete
/// are sugar that read-modify-put `features.vfs.workspaces`.
async fn put_workspace_attachment(
    api: &HttpAgentApi,
    session_id: String,
    attachment: api::WorkspaceAttachment,
) -> Result<api::SessionConfigPutResponse> {
    let session = api
        .read_session(api::SessionReadParams {
            session_id: session_id.clone(),
            run_limit: None,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result
        .session;
    let mut config = session
        .config
        .ok_or_else(|| anyhow::anyhow!("session is missing config"))?;
    let vfs = config
        .features
        .as_mut()
        .and_then(|features| features.vfs.as_mut())
        .ok_or_else(|| anyhow::anyhow!("session does not grant VFS"))?;
    vfs.workspaces
        .retain(|existing| existing.path != attachment.path);
    vfs.workspaces.push(attachment);
    Ok(api
        .put_session_config(api::SessionConfigPutParams {
            session_id,
            expected_config_revision: Some(session.config_revision),
            config,
        })
        .await
        .map_err(crate::api_client::api_error)?
        .result)
}

fn print_workspace_attachment(attachment: &api::WorkspaceAttachment) {
    let access = match attachment.access {
        api::WorkspaceAccess::Read => "read",
        api::WorkspaceAccess::Edit => "edit",
    };
    match (&attachment.workspace_id, &attachment.snapshot_ref) {
        (Some(workspace_id), _) => {
            println!("{} workspace {workspace_id} {access}", attachment.path);
        }
        (None, Some(snapshot_ref)) => {
            println!("{} snapshot {snapshot_ref} {access}", attachment.path);
        }
        (None, None) => println!("{} (no resource) {access}", attachment.path),
    }
}

async fn materialize(args: MaterializeArgs) -> Result<()> {
    let api = HttpAgentApi::new(args.api_url);
    let summary =
        materialize_snapshot(&api, args.snapshot_ref, args.workspace, args.destination).await?;
    if args.json {
        println!("{}", serde_json::to_string_pretty(&summary)?);
        return Ok(());
    }

    println!("snapshotRef {}", summary.snapshot_ref);
    println!("destination {}", summary.destination);
    println!("files {}", summary.files);
    println!("bytes {}", summary.bytes);
    println!("directories {}", summary.directories);
    println!("createdDirectories {}", summary.created_directories);
    println!("writtenFiles {}", summary.written_files);
    println!("writtenBytes {}", summary.written_bytes);
    println!("reusedFiles {}", summary.reused_files);
    println!("reusedBytes {}", summary.reused_bytes);
    println!("downloadedBlobs {}", summary.downloaded_blobs);
    println!("downloadedBytes {}", summary.downloaded_bytes);
    Ok(())
}

fn snapshot_options(args: &SnapshotArgs) -> SnapshotUploadOptions {
    SnapshotUploadOptions {
        limits: vfs::VfsSnapshotLimits::new(
            args.max_files,
            args.max_total_bytes,
            args.max_file_bytes,
            args.max_depth,
        ),
        max_put_many_batch_bytes: args.put_batch_bytes,
        max_put_many_batch_files: args.put_batch_files,
        max_has_many_refs: args.has_batch_refs,
    }
}
