import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile } from "json-schema-to-typescript";

const packageDir = path.dirname(fileURLToPath(import.meta.url));
const clientDir = path.resolve(packageDir, "..");
const interopDir = path.resolve(clientDir, "..");
const schemaPath = path.join(interopDir, "contract", "api.schema.json");
const methodsPath = path.join(interopDir, "contract", "methods.json");
const generatedDir = path.join(clientDir, "src", "generated");

const bannerComment = [
  "/*",
  " * Generated by interop/ts-client/scripts/generate.mjs.",
  " * Do not edit by hand.",
  " */",
  ""
].join("\n");

const types = await compileFromFile(schemaPath, {
  bannerComment,
  unreachableDefinitions: true,
  additionalProperties: false,
  enableConstEnums: false,
  style: {
    printWidth: 100,
    semi: true,
    singleQuote: false,
    trailingComma: "all"
  }
});

await writeFile(path.join(generatedDir, "types.ts"), types);

const manifest = JSON.parse(await readFile(methodsPath, "utf8"));
const methods = manifest.methods ?? [];
const notifications = manifest.notifications ?? [];

const seenAliases = new Map();

function typeNameFromRef(entry, method, side) {
  const ref = entry?.schema?.$ref;
  const prefix = "#/definitions/";
  if (typeof ref !== "string" || !ref.startsWith(prefix)) {
    throw new Error(`method ${method} ${side} schema is not a definitions ref`);
  }
  return ref.slice(prefix.length);
}

function methodAlias(method) {
  const parts = method.split(/[\/_-]+/).filter(Boolean);
  if (parts.length === 0) {
    throw new Error("empty method name");
  }
  const alias =
    parts[0] +
    parts
      .slice(1)
      .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
      .join("");
  const prior = seenAliases.get(alias);
  if (prior && prior !== method) {
    throw new Error(`method alias collision: ${alias} for ${prior} and ${method}`);
  }
  seenAliases.set(alias, method);
  return alias;
}

function q(value) {
  return JSON.stringify(value);
}

const methodLines = [
  bannerComment.trimEnd(),
  'import type * as Api from "./types.js";',
  "",
  "export const METHODS = [",
  ...methods.map((entry) => `  ${q(entry.method)},`),
  "] as const;",
  "",
  "export const NOTIFICATIONS = [",
  ...notifications.map((method) => `  ${q(method)},`),
  "] as const;",
  "",
  "export type Method = (typeof METHODS)[number];",
  "export type NotificationMethod = (typeof NOTIFICATIONS)[number];",
  "",
  "export interface MethodMap {",
  ...methods.flatMap((entry) => {
    const params = typeNameFromRef(entry.params, entry.method, "params");
    const result = typeNameFromRef(entry.result, entry.method, "result");
    return [
      `  ${q(entry.method)}: {`,
      `    params: Api.${params};`,
      `    result: Api.${result};`,
      "  };"
    ];
  }),
  "}",
  "",
  "export type MethodParams<M extends Method> = MethodMap[M][\"params\"];",
  "export type MethodResult<M extends Method> = MethodMap[M][\"result\"];",
  "",
  "export interface RpcCaller {",
  "  call<M extends Method>(method: M, params: MethodParams<M>): Promise<MethodResult<M>>;",
  "}",
  "",
  "export const rpc = {",
  ...methods.map((entry) => {
    const alias = methodAlias(entry.method);
    const params = typeNameFromRef(entry.params, entry.method, "params");
    const result = typeNameFromRef(entry.result, entry.method, "result");
    return `  ${alias}(client: RpcCaller, params: Api.${params}): Promise<Api.${result}> {\n    return client.call(${q(entry.method)}, params);\n  },`;
  }),
  "} as const;",
  ""
];

await writeFile(path.join(generatedDir, "methods.ts"), methodLines.join("\n"));
